# Generated by Django 4.0 on 2021-12-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='anioFund',
            field=models.DateField(),
        ),
    ]
