# Generated by Django 4.0 on 2021-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0002_alter_estadio_aniofund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dias_realizacion',
            field=models.DateField(),
        ),
    ]
