# Generated by Django 3.2.9 on 2022-01-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0003_alter_disciplina_dias_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
    ]
